package shared;

public enum SignalType {
	PRESSION_PUSHED,
	PRESSION_RELEASED,
	INVALID_POSITION,
	INVALID_DIRECTION,
	LOST, 
	UNHANDLED_ERROR,
	MASTERLIST_UPDATED, 
	STOP, 
	STALLED_ENGINE;
}
